<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../AlphaCarDetailing.Booking.Domain/AlphaCarDetailing.Booking.Domain.csproj" />
  </ItemGroup>
</Project>
